# Indie Studio Ads Optimizer: Predicting Premium Upgrade & Total Spend

## 1. Data Overview
Tujuan : Melihat dan mengenalkan data.

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("indie_studio_players.csv")
df.head()

,user_id,days_active,avg_session_time,community_engagement,total_spend,is_premium
0,1,137,228,73,365853,0
1,2,316,146,71,362463,1
2,3,112,128,44,259611,0
3,4,134,112,79,259588,0
4,5,222,45,7,144494,0

In [11]:
df.tail()

,user_id,days_active,avg_session_time,community_engagement,total_spend,is_premium
995,996,102,191,23,265288,0
996,997,69,58,50,87808,0
997,998,286,81,72,291620,1
998,999,264,69,85,228668,1
999,1000,55,112,50,208741,0

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   user_id               1000 non-null   int64
 1   days_active           1000 non-null   int64
 2   avg_session_time      1000 non-null   int64
 3   community_engagement  1000 non-null   int64
 4   total_spend           1000 non-null   int64
 5   is_premium            1000 non-null   int64
dtypes: int64(6)
memory usage: 47.0 KB

In [13]:
df.isnull().sum()

user_id                 0
days_active             0
avg_session_time        0
community_engagement    0
total_spend             0
is_premium              0
dtype: int64

Keterangan : Data bersih dan siap di analisis.

## 2. Basic Analysis

In [14]:
len(df[df["is_premium"] == 1])

308

In [15]:
len(df[df["is_premium"] == 0])

692